# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  #config.vm.provision "file", source: "config", destination: "config"
  config.vm.provision "shell", path: "provision.sh", privileged: "true"

  #config.vm.network "forwarded_port", protocol: "udp", guest: 53, host: 5353
  #config.vm.network "forwarded_port", protocol: "tcp", guest: 80, host: 8888

  # Configure for Vagrant VM lab (eth1) - Match production IP
  config.vm.network "private_network", ip: "10.1.1.21", :netmask => "255.255.255.0", :adapter => 2

  # 1.) Will not work after provision script is ran because of new kernel lacking guest additions
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.synced_folder ".", "/vagrant"
  # 2.) Will work becuase guest additions isn't a requirement
  # config.vm.synced_folder ".", "/vagrant", type: "rsync",
  # rsync__exclude: ".git/"
  # rsync_auto: "true" # Detect and copy any changes automatically

   config.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.name = "docker1"
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", 1]
   end

end
